name: pangenome_fox
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - ncbi-datasets-cli
  - pandas>=2.0
  - numpy>=1.24
  - scipy>=1.10
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - seaborn>=0.12
  - xgboost>=1.7
  - biopython>=1.80
  - pyyaml>=6.0
  - tqdm>=4.66
  - pytest
